spring:
  application:
    name: QPS-tuning
#  threads:
#    virtual:
#      enabled: true

redisson:
  sentinelServersConfig:
    masterName: ${REDIS_MASTER_NAME:mymaster}
    sentinelAddresses:
      - ${REDIS_SENTINEL_ADDRESS:redis://127.0.0.1:26379}
