apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: front-mpos
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'qps-tuning'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['qps-tuning-service:8080']
