apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: front-mpos
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        jsonData:
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo-service:3200
        jsonData:
          httpMethod: GET
          tracesToMetrics:
            datasourceUid: prometheus
            tags:
              - key: service.name
                value: job
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          search:
            hide: false
