apiVersion: v1
kind: ConfigMap
metadata:
  name: mps-redis-ha-config
  namespace: front-mpos
data:
  REDIS_POD_BASENAME: mps-redis-ha
  REDIS_HEADLESS_SERVICE: mps-redis-ha-headless
  REDIS_MASTER_NAME: mymaster
  REDIS_REPLICA_COUNT: "3"
  REDIS_PORT: "6379"
  SENTINEL_PORT: "26379"
  CLUSTER_DOMAIN: cluster.local

